name: Build friends.json

on:
  push:
    branches:
      - main
    paths:
      - 'src/friends.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js v22.14.0
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'

      - name: Install dependencies
        run: npm install

      - name: Build friends.json
        run: npm run build && tar -zcvf friends.tar.gz dist

      - name: Copy friends.json to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "friends.tar.gz"
          target: ${{ secrets.TARGET }}

      - name: Deploy applications
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd ${{ secrets.TARGET }}
            tar -zxvf friends.tar.gz